apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: app-sample
  name: app-sample
spec:
  containers:
  - image: yoonkwon23/kube-config:v2.4
    name: app-sample
    ports:
    - containerPort: 8090
    resources: {}
    env:
    - name: MESSAGE
      valueFrom:
        configMapKeyRef:
          name: sample-configmap
          key: message
    - name: SECRET-MESSAGE
      valueFrom:
        secretKeyRef:
          name: sample-secret
          key: secretmassage
  dnsPolicy: ClusterFirst
  restartPolicy: Always

