server:
  port: 8090
spring:
  profiles: local

sample:
  message: "Local message"
  secret-message: "Local secret message"

---
spring:
  profiles: stg

sample:
  message: ${MESSAGE}
  secret-message: ${SECRET-MESSAGE}